---
stages:
- Unit tests
- Build
- Release

variables:
  ECR: public.ecr.aws/equancy-tech
  IMAGE_NAME: datalake-catalog

pytest-api:
  stage: Unit tests
  only:
    changes:
      - datalake_catalog/**/*
      - tests/**/*
    refs:
      - branches
  image: public.ecr.aws/equancy-tech/ci-python:3.8
  before_script:
  - poetry install --quiet
  script:
  - poetry run coverage run -m pytest -m "not backends" -q --color=no
  - poetry run coverage report

pytest-backends:
  stage: Unit tests
  only:
    changes:
      - datalake_catalog/**/*
      - tests/**/*
    refs:
      - branches
  image: public.ecr.aws/equancy-tech/ci-python:3.8
  services:
    - alias: mariadb
      name: mariadb:10
    - alias: postgres
      name: postgres:13
  variables:
    MARIADB_USER: api
    MARIADB_PASSWORD: unittest
    MARIADB_DATABASE: catalog
    MARIADB_RANDOM_ROOT_PASSWORD: "true"
    POSTGRES_USER: api
    POSTGRES_PASSWORD: unittest
    POSTGRES_DB: catalog
  before_script:
  - poetry install --quiet --extras "all"
  script:
  - poetry run pytest -m "backends" -q --color=no

python-build:
  stage: Build
  only:
  - tags
  image: public.ecr.aws/equancy-tech/ci-python:3.8
  script:
  - poetry build --quiet
  cache:
    paths:
    - dist
    policy: push
  
pypi-publish:
  stage: Release
  only:
  - tags
  image: public.ecr.aws/equancy-tech/ci-python:3.8
  script:
  - poetry publish -u "${PYPI_USER}" -p "${PYPI_PASSWORD}"
  cache:
    paths:
    - dist
    policy: pull

docker-publish:
  stage: Release
  only:
  - tags
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
  - mkdir -p /kaniko/.docker
  - echo '{"credsStore":"ecr-login"}' > /kaniko/.docker/config.json
  script:
  - |
    /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --dockerfile $CI_PROJECT_DIR/Dockerfile \
      --destination "${ECR}/${IMAGE_NAME}:${CI_COMMIT_TAG}" \
      --single-snapshot
  cache:
    paths:
    - dist
    policy: pull

